# Generated by Django 6.0.4 on 2026-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_orderitem_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_window',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='gcash_reference_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='gcash_sender_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash')], default='COD', max_length=10),
        ),
    ]
