# Generated by Django 6.0.4 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_order_delivery_date_order_delivery_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(
                choices=[('delivery', 'Delivery'), ('pickup', 'Store Pickup')],
                default='delivery',
                max_length=20,
            ),
        ),
    ]
