# Generated by Django 6.0.2 on 2026-04-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
